select orderItem.id, 
	orderItem.orderKey, 
	orderItem.titleNo, 
	CONCAT_WS(',',t.titleId, t.title) AS titleNoSearch,
	t.titleId, 
	t.title, 
	orderItem.lInventory, 
	orderItem.lConsignment, 
	orderItem.itemCondtn, 
	orderItem.quantity, 
	orderItem.orderDate, 
	orderItem.price, 
	orderItem.discount, 
	orderItem.deduction, 
	orderItem.price - orderItem.deduction AS effPrice,
	ROUND((orderItem.price - orderItem.deduction) * orderItem.quantity, 2) AS extPrice,
	orderItem.shipWeight, 
	orderItem.itemStatus, 
	orderItem.lSubscript, 
	orderItem.expireDate, 
	orderItem.comment, 
	orderItem.updatedBy, 
	orderItem.userNo, 
	orderItem.lastUpdated 
from orderItem LEFT JOIN title t ON t.id = orderItem.titleNo
%where% %orderBy% %limit% ;
