select title.id, 
title.titleId, 
title.title, 
title.titleNoPre, 
title.subtitle, 
title.isbn, 
title.isbn13, 
title.ean13, 
title.upc, 
title.lccn, 
title.classId, 
title.supplierNo, 
concat_ws(",", suppl.lastName, suppl.firstName, suppl.company) as supplierNoSearch,
title.imprintNo, 
concat_ws(",", impr.lastName, impr.firstName, impr.company) as imprintNoSearch,
title.vendorNo, 
concat_ws(",", vend.lastName, vend.firstName, vend.company) as vendNoSearch,
title.vendorRole, 
title.lSubscript, 
title.lInventory, 
title.lConsignment,
title.lTaxable,
title.retPrice, 
title.cartonCount, 
title.cartonWgt, 
title.salesCount, 
title.bookLbs, 
title.bookOz, 
title.weight, 
title.weightUnit, 
title.pageCount, 
title.height, 
title.width, 
title.thickness, 
title.linearUnit, 
title.lBarCode, 
title.barcodetyp, 
title.shelfId, 
title.saftyStock, 
title.reordrQty, 
title.leadTime, 
title.lOutOfPrint, 
title.copyRtYear, 
title.edition, 
title.editionNo, 
title.pubStatus, 
title.pubDate, 
title.discCode, 
title.genre, 
title.audience, 
title.audRangTyp, 
title.audRange1, 
title.audRange2, 
title.language, 
title.formCode, 
title.formDetail, 
title.eFormURL, 
title.available, 
title.availDate, 
title.returnCode, 
title.collection, 
title.parentId, 
title.nameInSet, 
title.volumeNo, 
title.promoText, 
title.boComment, 
title.TOC, 
title.sampleText, 
title.imageFile, 
title.imageFile2, 
title.reviews, 
title.comment, 
title.lApproved, 
title.updatedBy, 
title.userNo, 
title.lastUpdated 
from title 
left join contact suppl ON suppl.id = title.supplierNo 
left join contact impr ON impr.id = title.imprintNo 
left join contact vend ON vend.id = title.vendorNo 
%where% %orderBy% %limit% ;
