
#	BISACS_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table bisacsubjectcodes;
	create table bisacsubjectcodes ( 
		id   		integer(10) primary key auto_increment, 
		bisaccode   varchar(11), 
		literal     varchar(112), 
		seq         varchar(5), 
		trans       varchar(6),
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);