
#	CARTON_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table carton;
	create table (cfilename) ( 
		id   		integer(10) primary key auto_increment,
		shipmentNo  integer(10), 
		cartonId   	varchar(20), 
		sequenceNo  integer(4), 
		cartonQty  	integer(10), 
		weight      decimal(10, 2), 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);