
#	CONTRI_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table contributor;
	create table contributor ( 
		id			integer(10) primary key auto_increment,
		titleId    	varchar(20), 
		contactNo   integer(10), 
		role        varchar(3), 
		contrBio    text, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);