
#	ERROR_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			8/5/2011 using MAKE_DBF.


	drop table error;
	create table error ( 
		id			integer(10) primary key auto_increment,
		progName   	text, 
		lineNo      integer(10), 
		errorNo     integer(10), 
		dataFile   	varchar(10), 
		recNo       integer(10), 
		errorTime  	datetime, 
		errorMsg   	text, 
		errorCode  	text);