
#	INTERV_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			11/6/2014 using MAKE_DBF.


	drop table interview;
	create table interview ( 
		id			integer(10) primary key auto_increment,
		intrviewNo  integer(10), 
		contactNo   integer(10), 
		surveyId   	varchar(20), 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);