#	ITEMTE_T.SQL -- Automatically generated by MAKE_DBF.
#					Procedure generated by Ron Lawrence on 11/10/94.
#	Modified to ZAP the itemtemp records if the file already exists.


	drop table ITEMTEMP.DBF;
    create table itemtemp ( 
		id			integer(10) primary key auto_increment,
		orderNo     integer(10), 
		invoiceNo   integer(2), 
		titleId    	varchar(10), 
		title       varchar(70), 
		inventory   boolean, 
		consignmnt  boolean, 
		condition   varchar( 1), 
		quantity    decimal(10, 2), 
		orderDate  	datetime, 
		price       decimal(10, 2), 
		discount    decimal(6, 2), 
		deduction   decimal(10, 2), 
		shipWeight  decimal(10, 2), 
		itemStatus  char(1), 
		expireDate  datetime, 
		comment     text, 
		updatedBy  	char(3), 
		userNo		integer(10),
		lastUpdated datetime);