
#	ITEMST_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table itemstatus;
	create table itemstatus ( 
		id			integer(10) primary key auto_increment,
		itemStatus  varchar(1), 
		pubStatus   varchar(2), 
		available   varchar(2), 
		ackcode     varchar(2))
