
#	MRKTCO_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table mrktcode;
	create table mrktcode ( 
		id			integer(10) primary key auto_increment,
		orderKey   	integer(10), 
		contactNo   integer(10), 
		code        varchar(4), 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);