
#	ORDERITEM.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table orderItem;
	create table orderItem ( 
		id			integer(10) primary key auto_increment,
		orderKey   	integer(10), 
		titleNo   	integer(10), 
		titleId    	varchar(20), 
		title       text, 
		lInventory  boolean, 
		lConsignment boolean, 
		lTaxable	boolean,
		itemCondtn  char(1), 
		quantity    decimal(10, 2), 
		orderDate  	datetime, 
		price       decimal(10, 2), 
		discount    decimal(6, 2), 
		deduction   decimal(10, 2), 
		shipWeight  decimal(10, 2), 
		itemStatus 	char(1), 
		lSubscript  boolean,
		expireDate  datetime, 
		comment     text, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);