
/*	ORDERS.SQL -- Creates a database table for orders.	*/

	drop table orders;
	create table orders ( 
		id			integer(10) primary key auto_increment,
		orderNo     integer(10), 
		invoiceNo   integer(2), 
		orderType  	varchar(1), 
		orderDate  	datetime, 
		custPONo    varchar(16), 
		supplierNo  integer(10), 
		customerNo  integer(10), 
		shipToNo  	integer(10), 
		shipToAddr  text, 
		lCreditCard boolean, 
		courier     varchar(25), 
		shipWeight  decimal(10, 2) NOT NULL DEFAULT 0.00, 
		shipCharge  decimal(10, 2) NOT NULL DEFAULT 0.00, 
		terms       varchar(20), 
		termsDesc  	varchar(20), 
		salesRepNo  integer(10), 
		discount    decimal(6, 2), 
		lTaxable    boolean, 
		stateTaxRate decimal(7, 3), 
		lTaxShip    boolean, 
		localTaxRate decimal(7, 3), 
		adjType1  	varchar(12), 
		adjustment1  decimal(10, 2) NOT NULL DEFAULT 0.00, 
		adjType2  	varchar(12), 
		adjustment2  decimal(10, 2) NOT NULL DEFAULT 0.00, 
		subtotal    decimal(10, 2) NOT NULL DEFAULT 0.00, 
		noTaxSubtotal decimal(10, 2) NOT NULL DEFAULT 0.00, 
		stateTax    decimal(10, 2) NOT NULL DEFAULT 0.00, 
		localTax    decimal(10, 2) NOT NULL DEFAULT 0.00, 
		total       decimal(10, 2) NOT NULL DEFAULT 0.00, 
		status      varchar(9), 
		priorState  varchar(9), 
		shipDate   	datetime, 
		batchNo     integer(10), 
		lProcessed  boolean, 
		comment     text, 
		lExported   boolean, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime,
		index (customerNo)
		);