
#	ORDERP_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table orderpay;
	create table orderpay ( 
		id			integer(10) primary key auto_increment,
		transactNo  integer(10), 
		orderKey   	integer(10), 
		amount      decimal(10, 2),
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);
