
#	PGS_US_T.SQL -- Automatically generated by MAKE_DBF.
#					Procedure generated by Ron Lawrence on 01/04/2000.


	drop table pgs_user.dbf;
	create table pgs_user	( 
		id			integer(10) primary key auto_increment,
		ownerCntct  integer(10), 
		dspInvStat  boolean, 
		shipImmed  	boolean, 
		recvImmed  	boolean, 
		autoBatch  	boolean, 
		forecast    boolean, 
		confirm     boolean, 
		traceDate  	boolean, 
		damageDisc  decimal(6, 2), 
		minAdjust  	decimal(10, 2), 
		adj1Dflt   	varchar(12), 
		adj2Dflt   	varchar(12), 
		fsLength   	integer(10), 
		freeFormAd  boolean, 
		resrvCount  integer(10), 
		financeChk  boolean, 
		reuseRecs   boolean, 
		packPrompt  boolean, 
		lastV1inv  	integer(10), 
		letterHead  text, 
		suprLtrHd  	boolean, 
		refrshKeys  boolean, 
		cno         varchar( 5), 
		rcd         varchar( 5), 
		uct         varchar( 1))
