
#	PIIGS_T.SQL -- Automatically generated by MAKE_DBF.
#					Procedure generated by Ron Lawrence on 01/16/97.

	drop table contact;
	CREATE table contact 	( 
						contactNo    integer(10), 
						company     varchar(33), 
						first_name  varchar(15), 
						last_name   varchar(25), 
						po_addr     text, 
						cour_addr   text, 
						city        varchar(0), 
						state_abbr  varchar(2), 
						country     varchar(20), 
						zip_code    varchar(10), 
						countyabbr  varchar(4), 
						biltocntct  integer(10), 
						phone       varchar(16), 
						phone2      varchar(20), 
						fedIdNo     varchar(11), 
						exclude     boolean, 
						comment     text, 
						author      boolean, 
						customer    boolean, 
						mail_list   boolean, 
						sales_rep   boolean, 
						supplier    boolean, 
						entered_by  varchar(3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table ctaxrate;
	CREATE table ctaxrate	( 
						state_abbr  varchar(2), 
						countyabbr  varchar(4), 
						countyname  varchar(20), 
						tax_rate    decimal(6, 2), 
						entered_by  varchar(3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table customer;
	CREATE table customer	( 
						customerNo  integer(10), 
						crcrd_vndr  varchar(16), 
						crcrd_acct  varchar(20), 
						crcrdexpdt  datetime, 
						salesrepNo  integer(10), 
						tax_exempt  boolean, 
						discount    decimal(6, 2), 
						terms       varchar(20), 
						terms_desc  varchar(20), 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table error;
	CREATE table error   	( 
						prog_name   text, 
						lineNo       integer(10), 
						errorNo      integer(10), 
						data_file   varchar(10), 
						error_date  datetime, 
						error_time  decimal(12, 4), 
						error_msg   text, 
						error_code  m)



	drop table inv_tran;
	CREATE table inv_tran	( 
						transactNo  integer(10), 
						trans_date  datetime, 
						itemNo       integer(10), 
						titleId    varchar(10), 
						condition   varchar( 1), 
						inv_state   varchar( 1), 
						quantity    decimal(10, 2), 
						accumQty   decimal(10, 2), 
						location    integer(10), 
						shipmentNo  integer(10), 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table itemrcpt;
	CREATE table itemrcpt	( 
						itemNo       integer(10), 
						receiptNo    integer(10), 
						remainQty  decimal(12, 4), 
						quantity    decimal(10, 2), 
						amount      decimal(10, 2), 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table key;
	CREATE table key     	( 
						entity      varchar( 8), 
						key_field   varchar(10), 
						alias       varchar(10), 
						last_key    integer(10), 
						verified    boolean);

	drop table ldgrtran;
	CREATE table ldgrtran	( 
						transactNo  integer(10), 
						trans_date  datetime, 
						transevent  varchar(10), 
						trans_type  varchar(12), 
						accountNo    integer(10), 
						acct_type   varchar( 1), 
						amount      decimal(10, 2), 
						order_key   integer(10), 
						itemNo       integer(10), 
						receiptNo    integer(10), 
						specNo       integer(10), 
						comment     text, 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table mrktcode;
	CREATE table mrktcode	( 
						order_key   integer(10), 
						contactNo    integer(10), 
						code        varchar( 4), 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);


	drop table ordercpt;
	CREATE table ordercpt	( 
						order_key   integer(10), 
						receiptNo    integer(10), 
						customerNo  integer(10), 
						ordertotal  decimal(10, 2), 
						order_paid  decimal(10, 2), 
						surcharges  decimal(10, 2), 
						srchg_paid  decimal(10, 2), 
						unapplied   decimal(10, 2), 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table orderpay;
	CREATE table orderpay	( 
						transactNo  integer(10), 
						order_key   integer(10), 
						amount      decimal(10, 2))



	drop table orders;
	CREATE table orders  	( 
						order_key   integer(10), 
						orderNo      integer(10), 
						invoiceNo    n(2), 
						order_type  varchar( 1), 
						order_date  datetime, 
						cust_poNo    varchar(16), 
						supplierNo  integer(10), 
						customerNo  integer(10), 
						shptocntct  integer(10), 
						shipToAddr   text, 
						creditcard  boolean, 
						courier     varchar(20), 
						shipweight  decimal(10, 2), 
						shipcharge  decimal(10, 2), 
						terms       varchar(20), 
						terms_desc  varchar(20), 
						salesrepNo  integer(10), 
						discount    decimal(6, 2), 
						taxable     boolean, 
						s_tax_rate  decimal(6, 2), 
						tax_ship    boolean, 
						c_tax_rate  decimal(6, 2), 
						adj_type_1  varchar(12), 
						adjustmnt1  decimal(10, 2), 
						adj_type_2  varchar(12), 
						adjustmnt2  decimal(10, 2), 
						subtotal    decimal(10, 2), 
						total       decimal(10, 2), 
						status      varchar( 9), 
						priorstate  varchar( 9), 
						ship_date   datetime, 
						batchNo      integer(10), 
						processed   boolean, 
						comment     text, 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table ordritem;
	CREATE table ordritem	( 
						itemNo       integer(10), 
						order_key   integer(10), 
						titleId    varchar(10), 
						title       text, 
						inventory   boolean, 
						consignmnt  boolean, 
						condition   varchar( 1), 
						quantity    decimal(10, 2), 
						order_date  datetime, 
						price       decimal(10, 2), 
						discount    decimal(6, 2), 
						deduction   decimal(10, 2), 
						shipweight  decimal(10, 2), 
						item_state  varchar( 1), 
						expiredate  datetime, 
						comment     text, 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table receipt;
	CREATE table receipt 	( 
						receiptNo    integer(10), 
						customerNo  integer(10), 
						recpt_date  datetime, 
						order_key   integer(10), 
						amount      decimal(10, 2), 
						fullpaymnt  boolean, 
						recpt_type  varchar(16), 
						crcrd_acct  varchar(20), 
						crcrdexpdt  datetime, 
						crcrd_auth  varchar(15), 
						itemized    boolean, 
						refund      boolean, 
						processed   boolean, 
						comment     text, 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table ryltyspc;
	CREATE table ryltyspc	( 
						specNo       integer(10), 
						titleId    varchar(10), 
						authorNo     integer(10), 
						threshold   integer(10), 
						discount    decimal(6, 2), 
						rate        decimal(6, 2), 
						net         boolean, 
						when_ordrd  boolean, 
						entered_by  varchar( 3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table shipment;
	CREATE table shipment	( 
						shipmentNo  integer(10), 
						order_key   integer(10), 
						ship_type   varchar(1), 
						ship_date   datetime, 
						comment     text, 
						entered_by  varchar(3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table srcomspc;
	CREATE table srcomspc	( 
						specNo       integer(10), 
						salesrepNo  integer(10), 
						customerNo  integer(10), 
						rate        decimal(6, 2), 
						when_ordrd  boolean, 
						entered_by  varchar(3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table titlcost;
	CREATE table titlcost	( 
						specNo       integer(10), 
						titleId    varchar(10), 
						orderQty   integer(10), 
						cost        decimal(10, 2), 
						discount    decimal(6, 2), 
						rate        decimal(6, 2), 
						when_ordrd  boolean, 
						entered_by  varchar(3), 
						userNo		integer(10),
		lastUpdated datetime);

	drop table title;
	CREATE table title   	( 
						titleId    varchar(10), 
						title       text, 
						inventory   boolean, 
						isbn        varchar(15), 
						supplierNo  integer(10), 
						consignmnt  boolean, 
						ret_price   decimal(10, 2), 
						carton_cnt  integer(10), 
						carton_wgt  n(3), 
						sales_cnt   integer(10), 
						book_lbs    n(2), 
						book_oz     n(4, 1), 
						saftystock  integer(10), 
						reordrqty   integer(10), 
						lead_time   integer(10), 
						outofprint  boolean, 
						accumexpns  decimal(10, 2), 
						genre       varchar(10), 
						comment     text, 
						entered_by  varchar(3), 
						userNo		integer(10),
		lastUpdated datetime);