
#	PROMOT_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table promotion;
	create table promotion ( 
		id			integer(10) primary key auto_increment,
		promoId    	varchar(10), 
		titleId    	varchar(20), 
		startDate  	datetime, 
		endDate    	datetime, 
		promotext   text, 
		imageFile   text, 
		price       decimal(10, 2), 
		discount    decimal(6, 2), 
		deduction   decimal(10, 2), 
		lExclusive  boolean, 
		lDisplay    boolean, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);