
#	QUESTI_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			11/6/2014 using MAKE_DBF.


	drop table question;
	create table question ( 
		id			integer(10) primary key auto_increment,
		surveyId   	varchar(20), 
		sequenceNo  integer(10), 
		question    text, 
		codeType   	varchar(10), 
		comment     text, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);