
#	RECPTYPE.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table recptype;
	create table recptype ( 
		id			integer(10) primary key auto_increment,
		recptType  	varchar(16), 
		lCreditCard boolean, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);