
#	REPORT_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table reports;
	create table reports ( 
		id			integer(10) primary key auto_increment,
		rptTitle   	varchar(40), 
		menuId     	varchar(20), 
		lStandard   boolean, 
		selectScr  	varchar(36), 
		query       text, 
		formName   	varchar(36), 
		summaryFlg  boolean, 
		workAreas   integer(1), 
		globlVars  	text, 
		messageLin  text, 
		comment     text, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);