
#	REVIEW_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			11/6/2014 using MAKE_DBF.


	drop table review;
	create table review ( 
		id			integer(10) primary key auto_increment,
		reviewNo    integer(10), 
		titleId    	varchar(20), 
		reviewerNo  integer(10), 
		review      text, 
		rating      integer(1), 
		intrviewNo  integer(10), 
		lApproved   boolean, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);