
#	RPT_NE_T.SQL -- Automatically generated by MAKE_DBF.
#					Procedure generated by Ron Lawrence on 10/23/97.



	drop table rpt_new;
	create table rpt_new ( 
		id			integer(10) primary key auto_increment,
		rpt_title   varchar(30), 
		menuId     	varchar(20), 
		lStandard   boolean, 
		selectScr  	varchar(12), 
		query       text, 
		formName   	varchar(12), 
		summaryflg  boolean, 
		workAreas   integer(1), 
		globlVars  	text, 
		messageLin  text, 
		comment     text, 
		enteredBy  	char(3), 
		userNo		integer(10),
		lastUpdated datetime);
