
#	RYLTYS_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table ryltyspc;
	create table ryltyspc ( 
		id			integer(10) primary key auto_increment,
		titleId    	varchar(20), 
		authorNo    integer(10), 
		threshold   integer(10), 
		discount    decimal(6, 2), 
		rate        decimal(6, 2), 
		net         boolean, 
		lWhenOrdrd  boolean, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);