
#	SCR_OB_T.SQL -- Automatically generated by MAKE_DBF.
#					Procedure generated by Ron Lawrence on 08/02/1995.



	drop table scr_obj;
	create table scr_obj  ( 
		id			integer(10) primary key auto_increment,
		screenName  varchar( 8), 
		objectName  varchar(12), 
		vpos        integer(10), 
		hpos        integer(10), 
		height      integer(10), 
		width       integer(10), 
		objectNo    integer(10), 
		optnCount	integer(2), 
		disabled    boolean, 
		enteredBy  	char(3), 
		userNo		integer(10),
		lastUpdated datetime);
