
#	SHIPME_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table shipment;
	create table shipment ( 
		id			integer(10) primary key auto_increment,
		shipmentNo  integer(10), 
		shipDate  	datetime, 
		orderKey   	integer(10), 
		cartonQty  	integer(10), 
		courier     varchar(25), 
		courierNo   integer(10), 
		trackingid  varchar(20), 
		bolId      	varchar(20), 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);