
#	SPONSR_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			11/6/2014 using MAKE_DBF.


	drop table sponsrshp;
	create table sponsrshp ( 
		id			integer(10) primary key auto_increment,
		sponsorNo   integer(10), 
		titleId    	varchar(20), 
		amount      decimal(10, 2), 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);