
#	SUBJEC_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table subject;
	create table subject ( 
		id			integer(10) primary key auto_increment,
		titleId    	varchar(20), 
		subjCode    varchar(17), 
		subjText    text, 
		codeSource  varchar(6), 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);