
#	SUPPLI_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table supplier;
	create table supplier ( 
		id			integer(10) primary key auto_increment,
		contactNo   integer(10), 
		billToId   	varchar(20), 
		shipToId   	varchar(20), 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);