
#	TITLEC_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			6/26/2014 using MAKE_DBF.


	drop table titlecode;
	create table titlecode ( 
		id			integer(10) primary key auto_increment,
		titleId    	varchar(20), 
		code        char(4), 
		rating      integer(1), 
		updatedBy 	varchar(20), 
		lastUpdated datetime)
