
#	TITLCO_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table titlcost;
	create table titlcost ( 
		id			integer(10) primary key auto_increment,
		titleId    	varchar(20), 
		orderQty   	integer(10), 
		cost        decimal(10, 2), 
		discount    decimal(6, 2), 
		net         boolean, 
		rate        decimal(6, 2), 
		lWhenOrdrd  boolean, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);