
#	TPACCO_T.SQL -- Creates a database table.
#			This procedure was automatically generated by Ron Lawrence on 
#			01/15/2017 using MAKE_DBF.


	drop table tpaccount;
	create table tpaccount ( 
		id			integer(10) primary key auto_increment,
		contactNo   integer(10), 
		accountId  	varchar(20), 
		comment     text, 
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);