
#	TRNSCN_T.SQL -- Automatically generated by MAKE_DBF.
#					Procedure generated by Ron Lawrence on 01/22/93.


	drop table trnscntc;
	create table trnscntc ( 
		id			integer(10) primary key auto_increment,
		mailCode    char(7), 
		contacType  char(1), 
		contactNo   integer(10)
		updatedBy 	varchar(20), 
		userNo		integer(10),
		lastUpdated datetime);
